config/routes.rb
Rails.application.routes.draw do
  root to: 'media#index'
  resources :application_settings, :copyrights, :copyright_holders, :description_types, :dictionary_searches,
    :application_filters, :glossaries, :keywords, :media_keyword_associations, :media_searches,
    :online_resources, :organizations, :pictures, :projects, :quality_types, :recording_orientations,
    :reproduction_types, :sources, :sponsors, :transformations, :videos, :statuses, :publishers  
  get 'admin', to: 'main#admin', as: 'admin'
  get 'sessions/filter_by/:id', to: 'sessions#filter_by', as: 'sessions_filter_by'
  get 'subtitles/:video_id/:language/:form', to: 'subtitles#index', as: 'subtitles', defaults: { form: 'script', language: 'bo' }
  get 'help', to: 'help#advanced_search', as: 'help_advanced_search'
  
  resources :capture_device_makers do
    resources :models, controller: 'capture_device_models'
  end
  resources :categories do
    member do
      get :contract
      get :expand
    end
    resources :children, controller: 'categories' do
      member do
        get :contract
        get :expand
      end
    end
    resources :counts, controller: 'cached_category_counts', only: 'index'
  end
  resources :documents do
    get 'by_title/:title.:format', to: 'documents#by_title'
  end
  resources :media_objects, as: 'media', controller: :media do
    resources :affiliations, :captions, :descriptions, :locations, :places
    resources :associations, controller: 'media_category_associations'
    resource :media_publisher, :workflow
    collection do
      get :rename_all
      post :goto
    end
    member do
      get :rename
      get :large
      get :full_size
      get :external
    end
    resources :rotations, only: [:index, :show, :create] do
      collection { get :status }
    end
    resources :topics do
      resources :associations, controller: 'media_category_associations'
    end
    resources :source_associations, controller: 'media_source_associations'
    resources :titles do
      resources :citations
      resources(:translations, as: 'translated_titles', controller: :translated_titles) { resources :citations }
    end
    resources :topic_associations, controller: 'media_category_associations'
  end
  resources :media_imports do
    collection do
      get :status
      post :confirm
    end
  end
  resources :media_processes do
    collection { get :status }
  end
  resources :metadata_sources, except: [:new, :create]
  resources :places do  
    member do
      get :pictures
      get :documents
      get :videos
    end
    resources :counts, controller: 'place_counts', only: 'index'
  end
  resources :renderers, controller: 'file_renderers'
  resources :topics do
    member do
      get :contract
      get :expand
      get :pictures
      get :documents
      get :videos
    end
  end
  resources(:videos) { member { get 'subtitles/:language/:form', to: 'videos#show', as: 'subtitles', defaults: { form: 'script', language: 'bo' } } }
  #match ':controller(/:action(/:id(.:format)))'
  #comatose_admin
  # comatose_root 'ndlb/pages'  
end

app/models/topic.rb
class Topic < SubjectsIntegration::Feature
  headers['Host'] = SubjectsIntegration::Feature.headers['Host'] if !SubjectsIntegration::Feature.headers['Host'].blank?
  self.element_name = 'feature'
  
  def is_childless?
    # making sure expand link does not show up when children don't have media
    self.children.detect { |c| Topic.find(c.id).media_count > 0 }.nil?
  end
  
  def media_category_associations
    MediaCategoryAssociation.where(:category_id => self.id)
  end
  
  def paged_media(limit, offset = nil, type = nil)
    if type.nil?
      media = Medium.where('cumulative_media_category_associations.category_id' => self.id).joins(:cumulative_media_category_associations).limit(limit).offset(offset).order('media.created_on DESC')
    else
      media = Medium.where('cumulative_media_category_associations.category_id' => self.id, 'media.type' => type).joins(:cumulative_media_category_associations).limit(limit).offset(offset).order('media.created_on DESC')
    end
    media
  end
  
  def media(options = {})
    type = options[:type]
    joins = options[:cumulative].nil? || options[:cumulative] ? :cumulative_media_category_associations : :media_category_associations
    conditions = {"#{joins.to_s}.category_id" => self.id}
    conditions['media.type'] = type if !type.nil?
    Medium.where(conditions).joins(joins).order('media.created_on DESC')
  end
    
  def media_count(type = nil, force_update = false)
    CachedCategoryCount.updated_count(self.id, type, force_update).count
  end
  
  def self.roots_with_media
    root_ids = Rails.cache.fetch('topics/roots_with_media', :expires_in => 1.day) { self.roots.select{ |topic| topic.media_count>0 }.collect(&:id) }
    root_ids.collect{ |i| Topic.find(i) }
  end
  
  def ancestor_and_self_ids
    self.ancestors.collect{|c| c.id.to_i} + [self.id.to_i]
  end
  
  def full_lineage
    self.ancestors.collect(&:header).join(' > ')
  end

  alias count_inherited_media media_count
  # This helps with calls to count media for generalized elements
  # alias :media_count :count_inherited_media
end

app/controllers/topics_controller.rb
class TopicsController < AclController
  helper :media
  cache_sweeper :media_category_association_sweeper, :only => [:destroy]
  
  def initialize
    super
    @current_tab_id = :browse
    @guest_perms += ['topics/pictures', 'topics/videos', 'topics/documents', 'topics/expand', 'topics/contract']
  end
  
  # GET /topics
  def index
    redirect_to topic_url(2823)
  end
    
  # GET /topics/1
  def show
    @topic = Topic.find(params[:id])
    @root = @topic.root
    medium_id = params[:medium_id]
    @margin_depth = params[:margin_depth].to_i
    @medium = nil
    if !medium_id.blank?
      begin
        @medium = Medium.find(medium_id)
      rescue ActiveRecord::RecordNotFound
        @medium = nil
      end
    end
    @pictures = @topic.media(:type => 'Picture').limit(Medium::COLS * Medium::PREVIEW_ROWS)
    @videos = @topic.media(:type => 'Video').limit(Medium::COLS * Medium::PREVIEW_ROWS)
    @documents = @topic.media(:type => 'Document').limit(Medium::COLS * Medium::PREVIEW_ROWS)
    render_media
  end
  
  # DELETE /topics/1
  def destroy
    @topic = Topic.find(params[:id])
    MediaCategoryAssociation.where(category_id: @topic.id).destroy_all
    redirect_to topic_url(@topic.parent)
  end

  # GET /topics/1/pictures
  def pictures
    get_media_by_type('Picture')
    @title = ts :in, :what => Picture.model_name.human(:count => :many).titleize, :where => @topic.header
    render_media
  end
  
  # GET /topics/1/videos
  def videos
    get_media_by_type('Video')
    @title = ts :in, :what => Video.model_name.human(:count => :many).titleize, :where => @topic.header
    render_media
  end
  
  # GET /topics/1/documents
  def documents
    get_media_by_type('Document')
    @title = ts :in, :what => Document.model_name.human(:count => :many).titleize, :where => @topic.header
    render_media
  end
  
  # GET /topics/1/expand
  def expand
    @topic = Topic.find(params[:id])
    @margin_depth = params[:margin_depth].to_i
  end

  # GET /topics/1/contract
  def contract
    @topic = Topic.find(params[:id])
    @margin_depth = params[:margin_depth].to_i
  end
  
  private
  
  def get_media_by_type(type)
    @topic = Topic.find(params[:id])
    @media = @topic.media(:type => type)
    filter = session[:filter]
    if filter.blank?
      count = @topic.media_count(type)
    else
      @media = @media.send(filter)
      count = @media.count
    end
    @media = @media.paginate(:page => params[:page], :per_page => params[:per_page] || Medium::FULL_COLS * Medium::FULL_ROWS, :total_entries => count)
    @pagination_params = { :category_id => @topic.id, :type => type }
  end
  
  def render_media
    respond_to do |format|
      format.html do
        get_tab_options
        if !@medium.nil?
          render :action => 'show_for_medium'
        elsif !@topic.nil?
          render(:action => @media.nil? ? 'index' : 'show')
        elsif
          render :action => 'index'
        end          
      end
      format.js   { render 'show' }
      format.xml  { render 'show' }
      format.json { render :json => Hash.from_xml(render_to_string(:action => 'show.xml.builder')) }
    end
  end
  
  def get_tab_options
    @tab_options ||= {}
    @tab_options[:counts] = tab_counts_for_element(@topic)
    @tab_options[:urls] = tab_urls_for_element(@topic) 
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_contracted.html.erb
<%= (Util::MARGIN * margin_depth).html_safe %>
<%  if contracted.is_childless?
	  (Util::MARGIN * margin_depth).html_safe %>
	  &#9674;
<%	else %>
<%=   link_to '+', expand_topic_path(contracted.id, :margin_depth => margin_depth), :remote => true, :class => 'collapsable' %>
<%  end %>
<%= link_to h(contracted.header).s, topic_path(contracted.id, :margin_depth => margin_depth), :remote => true %> (<%= number_with_delimiter contracted.media_count, :delimiter => ',' %>)<br/>

app/views/topics/_expanded.html.erb
<% if margin_depth.nil?
     margin_depth = expanded.ancestors.size
   end %>
<%= (Util::MARGIN * margin_depth).html_safe %>
<% childless = expanded.is_childless?
   if childless %>
     &#9674;
<% else %>
<%=  link_to '-', contract_topic_path(expanded.id, :margin_depth => margin_depth), :remote => true, :class => 'collapsable' %>
<% end
   selected = !@topic.nil? && (expanded.id == @topic.id)
   if selected %>
     <span class="selected_branch">
<% end %>
<%= link_to h(expanded.header).s, topic_path(expanded.id, :margin_depth => margin_depth), :remote => true %> (<%= number_with_delimiter expanded.media_count, :delimiter => ',' %>)
<% if selected %>
     </span>
<% end %>
<br/>
<% unless childless
	children = expanded.children.collect{ |c| Topic.find(c.id) }.select{|element| element.media_count > 0 } %>
<%= render :partial => 'topics_index', :locals => {:margin_depth => margin_depth+1, :topics => children} %>
<% end %>

app/views/topics/_media_index.html.erb
<% if !@pictures.nil? || !@videos.nil? || !@documents.nil?
     if !@topic.nil? %>
	   <h2><%= Medium.model_name.human(:count => :many).titleize.s %> Associated with <%= @topic.header %></h2>
<%   end %>
<%   no_media = true
     title = @topic.header
     if !@pictures.empty? %>
       <h3><%= ts(:in, :what => Picture.model_name.human(:count => :many).titleize, :where => title) %></h3>
<%     no_media = false %>
<%=    render :partial => 'media/media_table', :locals => { :media => @pictures, :more => pictures_topic_path(@topic.id) } %>
<%   end
     if !@videos.empty? %>
       <h3><%= ts(:in, :what => Video.model_name.human(:count => :many).titleize, :where => title) %></h3>
<%     no_media = false %>
<%=    render :partial => 'media/media_table', :locals => { :media => @videos, :more => videos_topic_path(@topic.id) } %>
<%   end
     if !@documents.empty? %>
       <h3><%= ts(:in, :what => Document.model_name.human(:count => :many).titleize, :where => title) %></h3>
<%     no_media = false %>
<%=    render :partial => 'documents/media_table', :locals => { :media => @documents, :more => documents_topic_path(@topic.id) } %>
<%   end
     if no_media %>
       <p><%= ts 'media.none' %></p>
<%   end %>
<% elsif !@media.nil? %>
<%=  render :partial => 'media/paged_index_full' %>
<% end %>
<p>
<%= link_to ts(:in, :what => @topic.header, :where => Topic.human_name(:count => :many).titleize), Topic.element_url(@topic.id, :format => '') %>
<%  path = topic_path(@topic.id)
    if authorized?(path, :action => 'destroy') && !@topic.nil? && @topic.media_count - @topic.media_category_associations.size <= 0 %>
      | <%= link_to "Delete all associations with #{Topic.human_name}", path, method: :delete, data: { confirm: te('delete.confirmation') } %>
<%  end %>
</p>

app/views/topics/_show.html.erb
<p><%= @topic.header %></p>

app/views/topics/_topics_index.html.erb
<% for topic in topics %>
   <div id="<%= "#{topic.id}_div" %>">
<%   if @current.nil? || @current.empty?  || (index = @current.index(topic.id.to_i)).nil? %>
<%=    render :partial => 'contracted', :object => topic, :locals => {:margin_depth => margin_depth} %>
<%   else
       @current.delete_at(index) %>
<%=    render :partial => 'expanded', :object => topic, :locals => {:margin_depth => margin_depth} %>
<%   end %>
   </div>
<% end %>

app/views/topics/contract.js.erb
$("#<%= @topic.id %>_div").html("<%= escape_javascript(render(:partial => 'contracted', :object => @topic, :locals => {:margin_depth => @margin_depth})) %>")

app/views/topics/expand.js.erb
$("#<%= @topic.id %>_div").html("<%= escape_javascript(render(:partial => 'expanded', :object => @topic, :locals => {:margin_depth => @margin_depth})) %>")

app/views/topics/index.html.erb
<% cache_key = { :controller => controller.controller_name, :action => controller.action_name, :locale => I18n.locale.to_s }
   cache_key[:id] = @topic.id if !@topic.nil?
   cache cache_key do
     @current = @topic.ancestor_and_self_ids if !@topic.nil? %>
     <div id="primary">
       <h4>Browse by <%= select_tag :root_topics, options_for_select((@root.nil? ? [''] : []) + Topic.roots_with_media.collect{|topic| [topic.header, topic_path(topic.id)]}, @root.nil? ? '' : topic_path(@root.id)) %></h4>
       <div id="navigation" class="normal">
<%       if !@root.nil? %>
<%=        render :partial => 'topics_index', :locals => {:topics => @root.children.collect{ |c| Topic.find(c.id) }.select{|element| element.media_count > 0}, :margin_depth => 0} %>
<%       end %>
       </div>
     </div>
<% end %>
<%= javascript_on_load do %>
      $("select[name='root_topics']").change(function() {
		  value = $(this).val();
		  if (value != '') window.location = value;
	  });
<%  end %>
<div id="secondary">
<%= render :partial => 'media_index' %>
</div>
<div class="clear"></div>

app/views/topics/show.html.erb
<div id="secondary">
<%= render :partial => 'topics/media_index' %>
</div>
<div class="clear"></div>

app/views/topics/show.js.erb
<% if !@medium.nil? %>
     $('#primary').html("<%= escape_javascript(render(:partial => 'media/show')) %>")
<% end %>
$('#secondary').html("<%= escape_javascript(render(:partial => 'media_index')) %>")
$('.selected_branch').removeClass('selected_branch')
$("#<%= @topic.id %>_div").html("<%= escape_javascript(render(:partial => 'expanded', :object => @topic, :locals => {:margin_depth => @margin_depth})) %>")

app/views/topics/show_for_medium.html.erb
<div id="primary">
<%= render :partial => 'media/show' %>
</div>
<div id="secondary">
<%=  render :partial => 'topics/media_index' %>
</div>
<div class="clear"></div>