config/routes.rb
Rails.application.routes.draw do
  root to: 'media#index'
  resources :application_settings, :copyrights, :copyright_holders, :description_types, :dictionary_searches,
    :application_filters, :glossaries, :keywords, :media_keyword_associations, :media_searches,
    :online_resources, :organizations, :pictures, :projects, :quality_types, :recording_orientations,
    :reproduction_types, :sources, :sponsors, :transformations, :videos, :statuses, :publishers  
  get 'admin', to: 'main#admin', as: 'admin'
  get 'sessions/filter_by/:id', to: 'sessions#filter_by', as: 'sessions_filter_by'
  get 'subtitles/:video_id/:language/:form', to: 'subtitles#index', as: 'subtitles', defaults: { form: 'script', language: 'bo' }
  get 'help', to: 'help#advanced_search', as: 'help_advanced_search'
  
  resources :capture_device_makers do
    resources :models, controller: 'capture_device_models'
  end
  resources :categories do
    member do
      get :contract
      get :expand
    end
    resources :children, controller: 'categories' do
      member do
        get :contract
        get :expand
      end
    end
    resources :counts, controller: 'cached_category_counts', only: 'index'
  end
  resources :documents do
    get 'by_title/:title.:format', to: 'documents#by_title'
  end
  resources :media_objects, as: 'media', controller: :media do
    resources :affiliations, :captions, :descriptions, :locations, :places
    resources :associations, controller: 'media_category_associations'
    resource :media_publisher, :workflow
    collection do
      get :rename_all
      post :goto
    end
    member do
      get :rename
      get :large
      get :full_size
      get :external
    end
    resources :rotations, only: [:index, :show, :create] do
      collection { get :status }
    end
    resources :topics do
      resources :associations, controller: 'media_category_associations'
    end
    resources :source_associations, controller: 'media_source_associations'
    resources :titles do
      resources :citations
      resources(:translations, as: 'translated_titles', controller: :translated_titles) { resources :citations }
    end
    resources :topic_associations, controller: 'media_category_associations'
  end
  resources :media_imports do
    collection do
      get :status
      post :confirm
    end
  end
  resources :media_processes do
    collection { get :status }
  end
  resources :metadata_sources, except: [:new, :create]
  resources :places do  
    member do
      get :pictures
      get :documents
      get :videos
    end
    resources :counts, controller: 'place_counts', only: 'index'
  end
  resources :renderers, controller: 'file_renderers'
  resources :topics do
    member do
      get :contract
      get :expand
      get :pictures
      get :documents
      get :videos
    end
  end
  resources(:videos) { member { get 'subtitles/:language/:form', to: 'videos#show', as: 'subtitles', defaults: { form: 'script', language: 'bo' } } }
  #match ':controller(/:action(/:id(.:format)))'
  #comatose_admin
  # comatose_root 'ndlb/pages'  
end

app/models/video.rb
# == Schema Information
#
# Table name: media
#
#  id                       :integer          not null, primary key
#  photographer_id          :integer
#  quality_type_id          :integer
#  created_on               :datetime
#  updated_on               :datetime
#  recording_note           :text
#  private_note             :text
#  type                     :string(20)       not null
#  attachment_id            :integer
#  taken_on                 :datetime
#  recording_orientation_id :integer
#  capture_device_model_id  :integer
#  partial_taken_on         :string(255)
#  application_filter_id    :integer          not null
#  resource_type_id         :integer          not null
#  rotation                 :integer
#

require 'fileutils'

class Video < Medium  
  include Util
  include ForkedNotifier

  validates_presence_of :attachment_id
  
  acts_as_indexable uid_prefix: MmsIntegration::MediaManagementResource.service, scope: {asset_type: self.name.downcase, service: MmsIntegration::Medium.service}

  before_create  { |record| record.resource_type_id = 2687 if record.resource_type_id.nil? }
  before_destroy { |record| record.movie.destroy }
  
  belongs_to :movie, :foreign_key => 'attachment_id'
  
  def attachment
    movie
  end
  
  def thumbnail_image
    att = attachment
    return nil if att.nil?
    att.children.find_by(thumbnail: 'thumb')
  end
  
  def screen_size_image
    attachment.children.find_by(thumbnail: 'preview')
  end
  
  def screen_size_movie
    movie.children.find_by(thumbnail: 'high')
  end

  def low_res_screen_size_movie
    movie.children.find_by(thumbnail: 'low')
  end
  
  def transcript
    movie.children.find_by(thumbnail: 'transcript')
  end
  
  # Requirements: gem rvideo, ffmpeg, x264, faac.
  def process(do_forking = true)
    parent = movie
    original = parent.full_filename
    bare_name = basename(parent.filename)
    pos = original.rindex('.')
    if pos>0
      path_and_name_without_extension =  original[0...pos]
    else
      path_and_name_without_extension = original
    end
    if RUBY_PLATFORM =~ /(:?mswin|mingw)/
      inspected_movie = nil
      width = 400
      height = 300
    else
      require 'rvideo'
      inspected_movie = RVideo::Inspector.new(:file => original)
      width = inspected_movie.width
      height = inspected_movie.height
    end
    if Video.generate_thumbnails(inspected_movie, width, height, original, path_and_name_without_extension)
      Movie.create(:content_type => 'image/jpeg', :filename => "#{bare_name}_compact.jpg", :parent_id => parent.id, :thumbnail => 'compact', :size => File.size("#{path_and_name_without_extension}_compact.jpg"), :width => 96, :height => 96) if File.exists?("#{path_and_name_without_extension}_compact.jpg")
      Movie.create(:content_type => 'image/jpeg', :filename => "#{bare_name}_thumb.jpg", :parent_id => parent.id, :thumbnail => 'thumb', :size => File.size("#{path_and_name_without_extension}_thumb.jpg"), :width => 120, :height => 120) if File.exists?("#{path_and_name_without_extension}_thumb.jpg")
      Movie.create(:content_type => 'image/jpeg', :filename => "#{bare_name}_preview.jpg", :parent_id => parent.id, :thumbnail => 'preview', :size => File.size("#{path_and_name_without_extension}_preview.jpg"), :width => width, :height => height) if File.exists?("#{path_and_name_without_extension}_preview.jpg")      
      high_res_movie = Movie.create :content_type => 'video/x-flv', :filename => "#{bare_name}_high.flv", :parent_id => parent.id, :thumbnail => 'high', :size => 0, :width => width, :height => height, :status => 0
      # low_res_movie = Movie.create :content_type => 'video/x-flv', :filename => "#{bare_name}_low.flv", :parent_id => parent.id, :thumbnail => 'low', :size => 0, :width => 200, :height => 150, :status => status
      high_res_movie_id = high_res_movie.id  
      # low_res_movie_id = low_res_movie.id
      background_process(do_forking) do
        Video.convert_to_flash_format(inspected_movie, original, path_and_name_without_extension)
        high_res_movie = Movie.find(high_res_movie_id)
        # low_res_movie = Movie.find(low_res_movie_id)
        high_res_movie.size = File.size("#{path_and_name_without_extension}_high.flv") if File.exists? "#{path_and_name_without_extension}_high.flv"
        # low_res_movie.size = File.size("#{path_and_name_without_extension}_low.flv") if File.exists? "#{path_and_name_without_extension}_low.flv"
        high_res_movie.status = 1
        high_res_movie.save
        # low_res_movie.status = 1
        # low_res_movie.save
      end
    end    
  end
    
  def self.maker_title
    'Videographer'
  end
  
  def self.caption_title
    'Title'
  end
  
  def self.public_folder
    'movies'
  end
  
  private
  
  def self.generate_thumbnails(inspected_movie, width, height, original, path_and_name_without_extension)
    cropped_sizes = {:compact => '96x96', :thumb => '120x120'}
    successful = true
    if inspected_movie.nil?
      cropped_sizes.each {|key, value| `ffmpeg -y -i #{original} -f image2 -ss 5 -vframes 1 -s #{value} -an #{path_and_name_without_extension}_#{key}.jpg` }
      `ffmpeg -y -i #{original} -f image2 -ss 5 -vframes 1 -s #{width}x#{height} -an #{path_and_name_without_extension}_preview.jpg`
    else
      duration_secs = inspected_movie.duration/1000
      half_way = duration_secs/2
      transcoder = RVideo::Transcoder.new
      recipe = 'ffmpeg -y -i $input_file$ -f image2 -ss $duration$ -vframes 1 -s $resolution$ -an $output_file$'
      begin
        cropped_sizes.each {|key, value| transcoder.execute(recipe, :input_file => original, :duration => half_way.to_s, :output_file => "#{path_and_name_without_extension}_#{key}.jpg", :resolution => value)}
        transcoder.execute(recipe, :input_file => original, :duration => half_way.to_s, :output_file => "#{path_and_name_without_extension}_preview.jpg", :resolution => "#{width}x#{height}")
      rescue RVideo::TranscoderError => e
        puts "Unable to transcode file: #{e.class} - #{e.message}" 
        successful = false
      end      
    end
    successful
  end
  
  def self.convert_to_flash_format(inspected_movie, original, path_and_name_without_extension)
    # `mencoder #{original} -ofps 8 -o #{path_and_name_without_extension}_low.flv -of lavf -oac mp3lame -lameopts abr:br=24 -srate 11025 -ovc lavc -lavfopts i_certify_that_my_video_stream_does_not_use_b_frames -lavcopts vcodec=flv:keyint=100:vbitrate=10:mbd=2:mv0:trell:v4mv:cbp:last_pred=3 -vf scale=200:150`
    # `mencoder #{original} -ofps 15 -o #{path_and_name_without_extension}_high.flv -of lavf -oac mp3lame -lameopts abr:br=64 -srate 22050 -ovc lavc -lavfopts i_certify_that_my_video_stream_does_not_use_b_frames -lavcopts vcodec=flv:keyint=150:vbitrate=150:mbd=2:mv0:trell:v4mv:cbp:last_pred=3 -vf scale=400:300`    
    #`cp #{original} #{path_and_name_without_extension}_high.flv`
    do_conversion = inspected_movie.nil? || (inspected_movie.video_codec!='h264' && FilenameUtils.extension_without_dot(original).downcase != 'flv')
    if do_conversion
      if inspected_movie.nil?
        `ffmpeg -i #{original} -sameq -vcodec libx264 -acodec libfaac #{path_and_name_without_extension}_high.flv`
        `flvtool2.bat -UP #{path_and_name_without_extension}_high.flv`  if File.exists? "#{path_and_name_without_extension}_high.flv"
        # `flvtool2.bat -UP #{path_and_name_without_extension}_low.flv` if File.exists? "#{path_and_name_without_extension}_low.flv"
      else
        begin
          transcoder.execute('ffmpeg -i $input_file$ -sameq -vcodec libx264 -acodec libfaac $output_file$', :input_file => original, :output_file => "#{path_and_name_without_extension}_high.flv")
        rescue RVideo::TranscoderError => e
          puts "Unable to transcode file: #{e.class} - #{e.message}"
        end
        `flvtool2 -UP #{path_and_name_without_extension}_high.flv` if File.exists? "#{path_and_name_without_extension}_high.flv"
        # `flvtool2 -UP #{path_and_name_without_extension}_low.flv` if File.exists? "#{path_and_name_without_extension}_low.flv"
      end
    else
      FileUtils.cp(original, "#{path_and_name_without_extension}_high.flv")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < AclController
  helper :media

  # GET /videos
  # GET /videos.xml
  def index
    @videos = Video.all
    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @videos.to_xml }
    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  def show
    @medium = Video.find(params[:id])
    if !@medium.transcript.nil?
      language = params[:language]
      form = params[:form]
      @transcript_params = {:video_id => @medium.id}
      @transcript_params[:language] = language if !language.nil?
      @transcript_params[:form] = form if !form.nil?
    end
    respond_to do |format|
      format.html # show.rhtml
      format.js
      format.xml  { render :xml => @medium.to_xml }
    end
  end

  # GET /videos/new
  def new
    @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
    @medium = Video.new(:resource_type_id => 2687)
    @photographers = AuthenticatedSystem::Person.order('fullname')
    @quality_types = QualityType.order('id')
    @recording_orientations = RecordingOrientation.order('title')
    @resource_types = Topic.find(2636).children
  end

  # GET /videos/1;edit
  def edit
    @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
    @medium = Video.find(params[:id])
    @photographers = AuthenticatedSystem::Person.order('fullname')
    @quality_types = QualityType.order('id')
    @recording_orientations = RecordingOrientation.order('title')          
    @resource_types = Topic.find(2636).children
    render :template => 'media/edit'
  end

  # POST /videos
  # POST /videos.xml
  def create
    @movie = Movie.new(params.require(:movie).permit(:content_type, :temp_path, :filename))
    success = @movie.save
    if success
      transcript_params = params[:transcript].permit(:content_type, :temp_path, :filename, :parent_id, :thumbnail)
      if !transcript_params.blank?
        transcript_params[:parent_id] = @movie.id
        transcript_params[:thumbnail] = 'transcript'
        transcript = Movie.new(transcript_params)
        success = transcript.save
      end
    end
    if success
      params_video = video_params
      @medium = Video.new(params_video)
      @medium.ingest_taken_on(params_video)
      @medium.movie = @movie
      success = @medium.save 
    end
    @medium.process if success
    respond_to do |format|
      if success
        flash[:notice] = ts('new.successful', :what => Video.model_name.human.capitalize)
        format.html { redirect_to medium_url(@medium) }
        format.xml  { head :created, :location => medium_url(@medium) }
      else
        format.html do
          @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
          @photographers = AuthenticatedSystem::Person.order('fullname')
          @quality_types = QualityType.order('id')
          @recording_orientations = RecordingOrientation.order('title')
          @resource_types = Topic.find(2636).children
          render :action => 'new'
        end
        format.xml  { render :xml => @video.errors.to_xml }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])
    respond_to do |format|
      if @video.update_attributes(params_video)
        flash[:notice] = ts('edit.successful', :what => Video.model_name.human.capitalize)
        format.html { redirect_to medium_url(@video) }
        format.xml  { head :ok }
      else
        format.html do
          @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
          @photographers = AuthenticatedSystem::Person.order('fullname')
          @quality_types = QualityType.order('id')
          @recording_orientations = RecordingOrientation.order('title')          
          @resource_types = Topic.find(2687).children          
          render :action => 'media/edit'
        end
        format.xml  { render :xml => @video.errors.to_xml }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def video_params
    params.require(:video).permit(:movie, :recording_note, :resource_type_id, :photographer_id, :taken_on,
    :capture_device_model_id, :quality_type_id, :private_note)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_show.html.erb
<%= javascript_include_tag 'mms_engine/swfobject' %>
<% movie = @medium.screen_size_movie
   relative_url = ActionController::Base.relative_url_root
   image = @medium.screen_size_image
   if movie.status==1
	 transcript_path = @medium.transcript.nil? ? nil : @transcript_params.nil? ? subtitles_path(@medium) : subtitles_path(@medium, @transcript_params) %>
     <p id="player1"><a href="http://www.macromedia.com/go/getflashplayer"><%= ts 'video.needs_flash' %></a></p>
     <script type="text/javascript">
	   var s1 = new SWFObject(<%= "\"#{relative_url}/flash/mediaplayer.swf\"" %>,"single","<%= movie.width %>","<%= movie.height + 20 %>","7");
	   s1.addParam("allowscriptaccess", "always");
	   s1.addParam("allowfullscreen", "true");
	   s1.addVariable("file",<%= "\"#{relative_url}#{movie.public_filename}\"" %>);
	   s1.addVariable("overstretch", "false");
	   s1.addVariable("image",<%= "\"#{relative_url}#{image.public_filename}\"" %>);
<%     if !transcript_path.nil? %>
         s1.addVariable("captions", <%= "\"#{relative_url}#{transcript_path}\"" %>);
<%     end %>
	   s1.write("player1");
     </script>
<%   if !transcript_path.nil? %>
	 <p>
<%=    link_to ts('tibetan.script'), subtitles_video_path(@medium, :language => 'bo'), :remote => true %> |
<%=    link_to ts('tibetan.transliteration'), subtitles_video_path(@medium, :language => 'bo', :form => 'transliteration'), :remote => true %> |
<%=    link_to ts(:english), subtitles_video_path(@medium, :language => 'en'), :remote => true %>
	 </p>
<%   end
   else %>
<%=  image_tag(image.public_filename) %>
     <p><%= ts 'video.not_ready' %></p>
<% end %>

app/views/videos/_show_external.html.erb
<%= javascript_include_tag 'mms_engine/swfobject' %>
<% movie = @medium.screen_size_movie
   server = root_url.chop
   image = @medium.screen_size_image
   if movie.status==1
	 transcript_path = @medium.transcript.nil? ? nil : @transcript_params.nil? ? subtitles_url(@medium) : subtitles_url(@medium, @transcript_params) %>
     <p id="player1"><a href="http://www.macromedia.com/go/getflashplayer"><%= ts 'video.needs_flash' %></a></p>
     <script type="text/javascript">
	   var s1 = new SWFObject(<%= "\"#{server}/flash/mediaplayer.swf\"" %>,"single","<%= movie.width %>","<%= movie.height + 20 %>","7");
	   s1.addParam("allowscriptaccess", "always");
	   s1.addParam("allowfullscreen", "true");
	   s1.addVariable("file",<%= "\"#{server}#{movie.public_filename}\"" %>);
	   s1.addVariable("overstretch", "false");
	   s1.addVariable("image",<%= "\"#{server}#{image.public_filename}\"" %>);
<%     if !transcript_path.nil? %>
         s1.addVariable("captions", <%= "\"#{server}#{transcript_path}\"" %>);
<%     end %>
	   s1.write("player1");
     </script>
<%   if !transcript_path.nil? %>
	 <p>
<%=    link_to ts('tibetan.script'), subtitles_video_url(@medium, :language => 'bo'), :remote => true %> |
<%=    link_to ts('tibetan.transliteration'), subtitles_video_url(@medium, :language => 'bo', :form => 'transliteration'), :remote => true %> |
<%=    link_to ts(:english), subtitles_video_url(@medium, :language => 'en'), :remote => true %>
	 </p>
<%   end
   else %>
<%=  image_tag(server + image.public_filename) %>
     <p><%= ts 'video.not_ready' %></p>
<% end %>

app/views/videos/index.html.erb
<h1><%= ts 'list.ing', :what => Video.model_name.human(:count => :many).titleize %></h1>
<table border="1" class="normal">
  <tr>
    <th><%= ts 'id.record', :what => Video.model_name.human.titleize %></th>
    <th><%= Video.human_attribute_name('photographer').s %></th>
    <th><%= QualityType.model_name.human.titleize.s %></th>
  </tr>
<% for video in @videos %>
  <tr>
    <td><%= link_to video.id, video_path(video) %></td>
    <td><%=h video.photographer.fullname if !video.photographer.nil? %></td>
    <td><%=h(video.quality_type.title).s %></td>
  </tr>
<% end %>
</table>
<p>
<%= link_to ts('new.record', :what => Video.model_name.human), new_video_path %>
</p>

app/views/videos/new.html.erb
<%= tinymce_assets %>
<%= tinymce %>
<h1><%= ts 'new.record', :what => 'Audio-Video' %></h1>
<%= error_messages_for :medium %>
<%= error_messages_for :video %>
<%= form_for(:medium, :url => videos_path, :html => {:multipart => true}) do |f| %>
      <p><b><%= Movie.model_name.human.titleize.s %></b><br />
<%=   file_field :movie, :uploaded_data %></p>
      <p><b><%= ts(:transcript) %></b><br />
<%=   file_field :transcript, :uploaded_data %></p>
<%=   f.collection_select(:recording_orientation_id, @recording_orientations, :id, :title, { :include_blank => true }, language_options) %> (<%= link_to ts('new.record', :what => RecordingOrientation.model_name.human), new_recording_orientation_path, { :target => '_blank' } %>)</p>
      <p><b><%= Medium.human_attribute_name('recording_note').s %></b><br />
<%=   f.text_area :recording_note, :rows => 5, :class => 'tinymce' %></p>
      <p><b><%= @medium.class.human_attribute_name(:photographer).s %></b><br />
<%=   f.collection_select(:photographer_id, @photographers, :id, :fullname, { :include_blank => true }, language_options) %> (<%= link_to ts('new.record', :what => AuthenticatedSystem::Person.model_name.human), new_authenticated_system_person_path, { :target => '_blank' } %>)</p>
      <p><b><%= @medium.class.human_attribute_name(:capture_device_model).s %></b><br />
<%=   f.select(:capture_device_model_id, @capture_device_models.collect {|m| [ "#{h(m.capture_device_maker.title)} - #{h(m.title)}", m.id ] }, { :include_blank => true }) %> (<%= link_to ts('manage.record', :what => CaptureDeviceMaker.model_name.human), capture_device_makers_path, { :target => '_blank' } %>)</p>
<%=   render :partial => 'media/form', :locals => {:f => f} %>
      <p><%= globalized_submit_tag 'creat.e.this' %></p>
<%  end %>
<p><%= link_to ts('back.to', :what => t('all.records', :what => Medium.model_name.human(:count => :many))), media_path %></p>

app/views/videos/show.html.erb
<div id="secondary">
<%=  display_if_not_blank Medium.human_attribute_name(:id).s, "#{@medium.id} (#{link_to ts(:url_for_reference), medium_path(@medium)})".html_safe %>
<%= render :partial => 'show' %>
<%= render :partial => 'media/persistent_links' %>
</div>
<div class="clear"></div>

app/views/videos/show.js.erb
$("#primary").html("<%= escape_javascript(render('media/show')) %>")