config/routes.rb
Rails.application.routes.draw do
  root to: 'media#index'
  resources :application_settings, :copyrights, :copyright_holders, :description_types, :dictionary_searches,
    :application_filters, :glossaries, :keywords, :media_keyword_associations, :media_searches,
    :online_resources, :organizations, :pictures, :projects, :quality_types, :recording_orientations,
    :reproduction_types, :sources, :sponsors, :transformations, :videos, :statuses, :publishers  
  get 'admin', to: 'main#admin', as: 'admin'
  get 'sessions/filter_by/:id', to: 'sessions#filter_by', as: 'sessions_filter_by'
  get 'subtitles/:video_id/:language/:form', to: 'subtitles#index', as: 'subtitles', defaults: { form: 'script', language: 'bo' }
  get 'help', to: 'help#advanced_search', as: 'help_advanced_search'
  
  resources :capture_device_makers do
    resources :models, controller: 'capture_device_models'
  end
  resources :categories do
    member do
      get :contract
      get :expand
    end
    resources :children, controller: 'categories' do
      member do
        get :contract
        get :expand
      end
    end
    resources :counts, controller: 'cached_category_counts', only: 'index'
  end
  resources :documents do
    get 'by_title/:title.:format', to: 'documents#by_title'
  end
  resources :media_objects, as: 'media', controller: :media do
    resources :affiliations, :captions, :descriptions, :locations, :places
    resources :associations, controller: 'media_category_associations'
    resource :media_publisher, :workflow
    collection do
      get :rename_all
      post :goto
    end
    member do
      get :rename
      get :large
      get :full_size
      get :external
    end
    resources :rotations, only: [:index, :show, :create] do
      collection { get :status }
    end
    resources :topics do
      resources :associations, controller: 'media_category_associations'
    end
    resources :source_associations, controller: 'media_source_associations'
    resources :titles do
      resources :citations
      resources(:translations, as: 'translated_titles', controller: :translated_titles) { resources :citations }
    end
    resources :topic_associations, controller: 'media_category_associations'
  end
  resources :media_imports do
    collection do
      get :status
      post :confirm
    end
  end
  resources :media_processes do
    collection { get :status }
  end
  resources :metadata_sources, except: [:new, :create]
  resources :places do  
    member do
      get :pictures
      get :documents
      get :videos
    end
    resources :counts, controller: 'place_counts', only: 'index'
  end
  resources :renderers, controller: 'file_renderers'
  resources :topics do
    member do
      get :contract
      get :expand
      get :pictures
      get :documents
      get :videos
    end
  end
  resources(:videos) { member { get 'subtitles/:language/:form', to: 'videos#show', as: 'subtitles', defaults: { form: 'script', language: 'bo' } } }
  #match ':controller(/:action(/:id(.:format)))'
  #comatose_admin
  # comatose_root 'ndlb/pages'  
end

app/models/capture_device_maker.rb
# == Schema Information
#
# Table name: capture_device_makers
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  exif_tag   :string(255)
#

class CaptureDeviceMaker < ActiveRecord::Base
  has_many :capture_device_models, -> { order 'title' }, dependent: :destroy
end

app/controllers/capture_device_makers_controller.rb
class CaptureDeviceMakersController < AclController
  # GET /capture_device_makers
  # GET /capture_device_makers.xml
  def index
    @capture_device_makers = CaptureDeviceMaker.order('title')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @capture_device_makers }
    end
  end

  # GET /capture_device_makers/1
  # GET /capture_device_makers/1.xml
  def show
    @capture_device_maker = CaptureDeviceMaker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @capture_device_maker }
    end
  end

  # GET /capture_device_makers/new
  # GET /capture_device_makers/new.xml
  def new
    @capture_device_maker = CaptureDeviceMaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @capture_device_maker }
    end
  end

  # GET /capture_device_makers/1/edit
  def edit
    @capture_device_maker = CaptureDeviceMaker.find(params[:id])
  end

  # POST /capture_device_makers
  # POST /capture_device_makers.xml
  def create
    @capture_device_maker = CaptureDeviceMaker.new(capture_device_maker_params)

    respond_to do |format|
      if @capture_device_maker.save
        flash[:notice] = ts('new.successful', :what => CaptureDeviceMaker.model_name.human.capitalize)
        format.html { redirect_to capture_device_makers_url }
        format.xml  { render :xml => @capture_device_maker, :status => :created, :location => @capture_device_maker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @capture_device_maker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /capture_device_makers/1
  # PUT /capture_device_makers/1.xml
  def update
    @capture_device_maker = CaptureDeviceMaker.find(params[:id])

    respond_to do |format|
      if @capture_device_maker.update_attributes(capture_device_maker_params)
        flash[:notice] = ts('edit.successful', :what => CaptureDeviceMaker.model_name.human.capitalize)
        format.html { redirect_to capture_device_makers_url }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @capture_device_maker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /capture_device_makers/1
  # DELETE /capture_device_makers/1.xml
  def destroy
    @capture_device_maker = CaptureDeviceMaker.find(params[:id])
    @capture_device_maker.destroy
    respond_to do |format|
      format.html { redirect_to(capture_device_makers_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def capture_device_maker_params
    params.require(:capture_device_maker).permit(:title, :exif_tag)
  end
end

app/helpers/capture_device_makers_helper.rb
module CaptureDeviceMakersHelper
end

app/views/capture_device_makers/_form.html.erb
<p>
  <b><%= CaptureDeviceMaker.human_attribute_name('title').s %></b><br />
  <%= f.text_field :title %>
</p>
<p>
  <b><%= CaptureDeviceMaker.human_attribute_name('exif_tag').s %></b><br />
  <%= f.text_field :exif_tag %>
</p>

app/views/capture_device_makers/_persistent_links.html.erb
<%  path = capture_device_maker_path(@capture_device_maker)
    if authorized?(path, :action => 'destroy') %>
<%=   link_to ts('delete.this'), path, method: :delete, data: { confirm: te('delete.confirmation') } %> |
<%  end %>
<%= link_to ts('back.to', :what => CaptureDeviceMaker.model_name.human(:count => :many)), capture_device_makers_path %> |
<%= render :partial => 'main/back_to_admin_or_media' %>

app/views/capture_device_makers/edit.html.erb
<h1><%= ts 'edit.ing.record', :what => CaptureDeviceMaker.model_name.human.titleize %></h1>
<%= error_messages_for :capture_device_maker %>
<%= form_for(@capture_device_maker) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
  <p>
<%= globalized_submit_tag 'update.this' %>
  </p>
<% end %>
<p>&nbsp;<br/>
<%= render :partial => 'persistent_links' %>
</p>

app/views/capture_device_makers/index.html.erb
<h1><%= ts 'list.ing.records', :what => CaptureDeviceMaker.model_name.human(:count => :many).titleize %></h1>
<table border="1" class="normal">
  <tr>
    <th><%= CaptureDeviceMaker.model_name.human.titleize.s %></th>
    <th><%= CaptureDeviceMaker.human_attribute_name('exif_tag').s %></th>
    <th><%= CaptureDeviceModel.model_name.human(:count => :many).titleize.s %></th>
  </tr>
<% for capture_device_maker in @capture_device_makers
	 path = edit_capture_device_maker_path(capture_device_maker) %>
  <tr>
    <td><%= authorized?(path) ? link_to(h(capture_device_maker.title), path) : link_to(h(capture_device_maker.title), capture_device_maker_path(capture_device_maker)) %></td>
    <td><%= capture_device_maker.exif_tag %></td>
    <td>
<%= capture_device_maker.capture_device_models.collect do |model|
      path = edit_capture_device_maker_model_path(capture_device_maker, model)
      authorized?(path) ? link_to(h(model.title), path) : link_to(h(model.title), capture_device_maker_model_path(capture_device_maker, model))
	end .join(', ').html_safe %></td>
<%  path = new_capture_device_maker_model_path(capture_device_maker)
    if authorized? path %>
	  <td><%= link_to ts('new.record', :what => CaptureDeviceModel.model_name.human), path %></td>
<% end %>
  </tr>
<% end %>
</table>
<p>&nbsp;<br/>
<% path = new_capture_device_maker_path
   if authorized? path %>
<%=  link_to ts('new.record', :what => CaptureDeviceMaker.model_name.human), path %> |
<% end %>
<%= render :partial => 'main/back_to_admin_or_media' %>
</p>

app/views/capture_device_makers/new.html.erb
<h1><%= ts 'new.record', :what => CaptureDeviceMaker.model_name.human.titleize %></h1>
<%= error_messages_for :capture_device_maker %>
<%= form_for(@capture_device_maker) do |f| %>
<%=   render :partial => 'form', :locals => {:f => f} %>
      <p><%= globalized_submit_tag 'creat.e.this' %></p>
<%  end %>
<p>&nbsp;<br/>
<%= link_to ts('cancel.record', :what => t('new.this')), capture_device_makers_path %> |
<%= render :partial => 'main/back_to_admin_or_media' %></p>

app/views/capture_device_makers/show.html.erb
<%= display_if_not_blank CaptureDeviceMaker.human_attribute_name('title').s, h(@capture_device_maker.title).s %>
<%= display_if_not_blank CaptureDeviceMaker.human_attribute_name('exif_tag').s, h(@capture_device_maker.exif_tag).s %>
<%= display_if_not_blank CaptureDeviceModel.model_name.human(:count => :many).s, capture_device_maker.capture_device_models.collect{|model| h(model.title)}.join(', ') %>
<p>&nbsp;<br/>
<% path = edit_capture_device_maker_path(@capture_device_maker)
   if authorized? path %>
<%=  link_to ts('edit.this'), path %> |
<% end %>
<%= render :partial => 'persistent_links' %>
</p>