config/routes.rb
Rails.application.routes.draw do
  root to: 'media#index'
  resources :application_settings, :copyrights, :copyright_holders, :description_types, :dictionary_searches,
    :application_filters, :glossaries, :keywords, :media_keyword_associations, :media_searches,
    :online_resources, :organizations, :pictures, :projects, :quality_types, :recording_orientations,
    :reproduction_types, :sources, :sponsors, :transformations, :videos, :statuses, :publishers  
  get 'admin', to: 'main#admin', as: 'admin'
  get 'sessions/filter_by/:id', to: 'sessions#filter_by', as: 'sessions_filter_by'
  get 'subtitles/:video_id/:language/:form', to: 'subtitles#index', as: 'subtitles', defaults: { form: 'script', language: 'bo' }
  get 'help', to: 'help#advanced_search', as: 'help_advanced_search'
  
  resources :capture_device_makers do
    resources :models, controller: 'capture_device_models'
  end
  resources :categories do
    member do
      get :contract
      get :expand
    end
    resources :children, controller: 'categories' do
      member do
        get :contract
        get :expand
      end
    end
    resources :counts, controller: 'cached_category_counts', only: 'index'
  end
  resources :documents do
    get 'by_title/:title.:format', to: 'documents#by_title'
  end
  resources :media_objects, as: 'media', controller: :media do
    resources :affiliations, :captions, :descriptions, :locations, :places
    resources :associations, controller: 'media_category_associations'
    resource :media_publisher, :workflow
    collection do
      get :rename_all
      post :goto
    end
    member do
      get :rename
      get :large
      get :full_size
      get :external
    end
    resources :rotations, only: [:index, :show, :create] do
      collection { get :status }
    end
    resources :topics do
      resources :associations, controller: 'media_category_associations'
    end
    resources :source_associations, controller: 'media_source_associations'
    resources :titles do
      resources :citations
      resources(:translations, as: 'translated_titles', controller: :translated_titles) { resources :citations }
    end
    resources :topic_associations, controller: 'media_category_associations'
  end
  resources :media_imports do
    collection do
      get :status
      post :confirm
    end
  end
  resources :media_processes do
    collection { get :status }
  end
  resources :metadata_sources, except: [:new, :create]
  resources :places do  
    member do
      get :pictures
      get :documents
      get :videos
    end
    resources :counts, controller: 'place_counts', only: 'index'
  end
  resources :renderers, controller: 'file_renderers'
  resources :topics do
    member do
      get :contract
      get :expand
      get :pictures
      get :documents
      get :videos
    end
  end
  resources(:videos) { member { get 'subtitles/:language/:form', to: 'videos#show', as: 'subtitles', defaults: { form: 'script', language: 'bo' } } }
  #match ':controller(/:action(/:id(.:format)))'
  #comatose_admin
  # comatose_root 'ndlb/pages'  
end

app/models/document.rb
# == Schema Information
#
# Table name: media
#
#  id                       :integer          not null, primary key
#  photographer_id          :integer
#  quality_type_id          :integer
#  created_on               :datetime
#  updated_on               :datetime
#  recording_note           :text
#  private_note             :text
#  type                     :string(20)       not null
#  attachment_id            :integer
#  taken_on                 :datetime
#  recording_orientation_id :integer
#  capture_device_model_id  :integer
#  partial_taken_on         :string(255)
#  application_filter_id    :integer          not null
#  resource_type_id         :integer          not null
#  rotation                 :integer
#

class Document < Medium  
  include MediaProcessor::DocumentExtension
  
  acts_as_indexable uid_prefix: MmsIntegration::MediaManagementResource.service, scope: {asset_type: self.name.downcase, service: MmsIntegration::Medium.service}
  
  before_create  { |record| record.resource_type_id = 2639 if record.resource_type_id.nil? }
  before_destroy { |record| record.typescript.destroy if !record.typescript.nil? }
  
  # The preview is generated in the highest possible resolution.  
  PREVIEW_TYPE = :huge
  belongs_to :typescript, :foreign_key => 'attachment_id'
  
  def attachment
    typescript
  end
    
  def self.public_folder
    'typescripts'
  end
  
  def preview_image
    typescript = self.typescript
    return typescript.nil? ? nil : typescript.children.find_by(thumbnail: PREVIEW_TYPE.to_s)
  end
    
  def self.paged_media_search(media_search, limit = 10, offset = 0)
    super(media_search, limit, offset, 'Document')
  end
end

app/controllers/documents_controller.rb
class DocumentsController < AclController
  helper :media
  caches_page :show, :if => Proc.new { |c| c.request.format.xml? }
  cache_sweeper :document_sweeper, :only => [:update, :destroy]

  def initialize
    super
    @guest_perms += ['documents/by_title']
  end

  # GET /documents
  # GET /documents.xml
  def index
    title = params[:title]
    if title.blank?
      original_medium_id = params[:original_medium_id]
      @documents = original_medium_id.blank? ? Document.all : Document.joins(:workflow).where('workflows.original_medium_id' => original_medium_id)
    else
      @documents = Document.joins(:titles).where('titles.title' => title) + Document.joins(:titles => :translated_titles).where('translated_titles.title' => title)
    end
    respond_to do |format|
      format.html # index.rhtml
      format.xml  # { render :xml => @documents.to_xml }
      format.ris
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @medium = Document.find(params[:id])
    if request.xhr?
      render :partial => 'media/show'
    else
      respond_to do |format|
        format.html # show.rhtml
        format.xml { render 'media/show' }
        format.ris
      end
    end
  end

  # GET /documents/new
  def new
    @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
    @medium = Document.new(:resource_type_id => 2639)
    @photographers = AuthenticatedSystem::Person.order('fullname')
    @quality_types = QualityType.order('id')
    @recording_orientations = RecordingOrientation.order('title')    
    @resource_types = Topic.find(2636).children
    @transformations = Transformation.order('renderer_id, title')
  end

  # GET /documents/1;edit
  def edit
    @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
    @medium = Document.find(params[:id])
    @photographers = AuthenticatedSystem::Person.order('fullname')
    @quality_types = QualityType.order('id')
    @recording_orientations = RecordingOrientation.order('title')    
    @resource_types = Topic.find(2636).children
    @transformations = Transformation.order('renderer_id, title')
    @root_topics = Topic.roots
    render :template => 'media/edit'
  end

  # POST /documents
  # POST /documents.xml
  def create
    typescript_params = params[:typescript].nil? ? nil : params.require(:typescript).permit(:content_type, :temp_path, :filename, :parent_id, :thumbnail)
    @typescript = nil
    if !typescript_params.nil? && !typescript_params[:uploaded_data].nil?
      @typescript = Typescript.new(typescript_params)
      success = @typescript.save
      has_typescript = true
    else
      has_typescript = false
      success = true
    end
    has_preview = false
    if success
      thumbnail_params = params[:thumbnail].nil? ? nil : params[:thumbnail].permit(:content_type, :temp_path, :filename, :parent_id, :thumbnail)
      if !thumbnail_params.nil? && !thumbnail_params[:uploaded_data].nil?
        # If thumbnail preview was given, use that as the original preview.
        if has_typescript
          thumbnail_params[:parent_id] = @typescript.id
          thumbnail_params[:thumbnail] = Document::PREVIEW_TYPE.to_s
        end
        thumbnail = Typescript.new(thumbnail_params)
        success = thumbnail.save
        if success
          if has_typescript
            has_preview = true
          else            
            @typescript = thumbnail
            has_typescript = true
          end
        end
      end
    end
    if success
      # creating medium before thumbnail to get id name.
      params_medium = params[:medium].permit(:recording_note, :resource_type_id, :photographer_id, :taken_on,
        :partial_taken_on, :capture_device_model_id, :quality_type_id, :private_note)
      params_medium = document_params if params_medium.nil?
      @medium = Document.new(params_medium)
      @medium.ingest_taken_on(params_medium)
      @medium.typescript = @typescript
      success = @medium.save
    end
    if success
      has_preview = @medium.create_or_update_preview if has_typescript && !has_preview
      @medium.create_thumbnails if has_preview
    end
    respond_to do |format|
      if success
        flash[:notice] = ts('new.successful', :what => Document.model_name.human.capitalize)
        format.html { redirect_to document_url(@medium) }
        format.xml  { head :created, :location => document_url(@medium) }
      else
        format.html do
          @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
          @photographers = AuthenticatedSystem::Person.order('fullname')
          @quality_types = QualityType.order('id')
          @recording_orientations = RecordingOrientation.order('title')    
          @resource_types = Topic.find(2636).children
          @transformations = Transformation.order('renderer_id, title')
          render :action => 'new'
        end
        format.xml  { render :xml => @medium.errors.to_xml }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.xml
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(document_params)
        flash[:notice] = ts('edit.successful', :what => Document.model_name.human.capitalize)
        format.html { redirect_to document_url(@document) }
        format.xml  { head :ok }
      else
        format.html do
          @capture_device_models = CaptureDeviceMaker.order('title').collect{|maker| maker.capture_device_models}.flatten
          @photographers = AuthenticatedSystem::Person.order('fullname')
          @quality_types = QualityType.order('id')
          @recording_orientations = RecordingOrientation.order('title')    
          @resource_types = Topic.find(2636).children
          @transformations = Transformation.order('renderer_id, title')
          render :action => 'edit'
        end
        format.xml  { render :xml => @document.errors.to_xml }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def document_params
    params.requre(:document).permit(:typescript, :recording_note, :resource_type_id, :photographer_id,
    :taken_on, :capture_device_model_id, :quality_type_id, :private_note)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_media_table.html.erb
<table border="0" cellpadding="0px" cellspacing="5px" id="picframe">
<% for medium in media
	 next if medium.nil? %>
     <tr align="center" valign="middle">
<%=  render :partial => 'documents/thumb_column', :locals => {:medium => medium} %>
     </tr>
<% end %>
   </tr>
<% if !more.nil? %>
     <tr>
   	   <td colspan="<%= Medium::COLS %>" align="right" class="media_keywords"><%= link_to 'More', more.is_a?(String) ? more : media_path(more) %></td>
     </tr>
<% end %>
</table>

app/views/documents/_paged_index.html.erb
<%= render :partial => 'documents/paged_table', :locals => { :media => @media, :title => @title } %>
<%  if !@media.empty? %>
<%=   render :partial => 'media/paged_links', :locals => { :media => @media } %>
<%  end %>

app/views/documents/_show.html.erb
<%= render :partial => 'pictures/show' %>
<%  typescript = @medium.typescript
    url = (!typescript.nil? && typescript.content_type == 'application/pdf') ? typescript.public_filename : nil
    if !url.nil? %>
      <br/>
      <p><%= link_to(ts(:get, :what => Document.model_name.human), url) %></p>
<%  end %>

app/views/documents/_show.ris.erb
TY - <%= medium.resource_type.codes.select{|c| c.code_type == 'RIS'}.first.value %>
M3 - <%= medium.resource_type.header %>
U5 - <%= medium.id %>
<% titles = medium.titles
   title = nil
   if titles.size == 1
		 title = titles.first.title
	 elsif titles.size > 1
		 title = "#{titles.first.title.html_safe} (#{titles.second.title.html_safe})"
   end
   if !title.blank? %>
TI - <%= title %>
<% end
   translated_titles = titles.collect{|t| t.translated_titles}.flatten
	 title = translated_titles.first
   if !title.blank? -%>
TT - <%= title.title.html_safe %>
<% end
   if !medium.photographer.nil? -%>
AU - <%= medium.photographer.fullname.html_safe %>
<% end 
   if !medium.media_publisher.nil? && !medium.media_publisher.publisher.nil? && !medium.media_publisher.publisher.title.blank? -%>
PB - <%= medium.media_publisher.publisher.title.html_safe %>
<% end
   partial_taken_on = medium.partial_taken_on
	 date = nil
	 year = nil
	 if partial_taken_on.nil?
		 taken_on = medium.taken_on
		 if !taken_on.nil?
			 date = medium.taken_on_display_string
			 year = taken_on.year
		 end
	 else
		 date = partial_taken_on
		 year = partial_taken_on.split('/').last
	 end
   if !year.blank? -%>
PY - <%= year %>
<% end 
if !date.blank? -%>
DA - <%= date %>
<% end 
   caption = medium.captions.first
	 if !caption.nil? && !caption.title.blank? -%>
CA - <%= caption.title.html_safe %>
<% end 
   desc = medium.descriptions.first
   if !desc.nil? && !desc.title.blank? -%>
N1 - <%= desc.title.html_safe %>
<% elsif !medium.recording_note.blank? -%>
N1 - <%= medium.recording_note.html_safe %>
<% end
   location = medium.locations.first
   if !location.nil? && !location.feature.nil? && !location.feature.header.blank? -%>
CY - <%= location.feature.header.html_safe %>
<% end
   medium.media_category_associations.each do |mca|
     if !mca.category.nil? && !mca.category.header.blank? -%>
KW - <%= mca.category.header.html_safe %>
<%   end
	 end -%>
ER -

app/views/documents/_show_external.html.erb
<%= render 'pictures/show_external' %>
<%  typescript = @medium.typescript
    url = (!typescript.nil? && typescript.content_type == 'application/pdf') ? root_url.chop + typescript.public_filename : nil
    if !url.nil? %>
      <br/>
      <p><%= link_to(ts(:get, :what => Document.model_name.human), url) %></p>
<%  end %>

app/views/documents/_thumb_column.html.erb
<% thumbnail = medium.thumbnail_image
   if thumbnail.nil? %>
     <td>&nbsp;</td>
<% else %>
     <td width="<%= thumbnail.width %>" height="<%= thumbnail.height %>">
<%=    link_to image_tag(thumbnail.public_filename, :width => thumbnail.width, :height => thumbnail.height), medium_path(medium), :class => 'media-thumb', :remote => true %>
     </td>
<% end %>
<td align="left" class="normal"><%= link_to medium.prioritized_title.s, medium_path(medium), :class => 'media-thumb', :remote => true %></td>

app/views/documents/index.html.erb
<h1><%= ts 'list.ing.records', :what => Document.model_name.human(:count => :many).titleize %></h1>
<table border="1" class="normal">
  <tr>
  </tr>
<% for document in @documents %>
  <tr>
    <td><%= link_to ts('show.this'), document_path(document) %></td>
    <td><%= link_to ts('edit.this'), edit_document_path(document) %></td>
    <td><%= link_to ts('delete.this'), document_path(document), method: :delete, data: { confirm: te('delete.confirmation') } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to ts('new.record', :what => Document.model_name.human), new_document_path %>

app/views/documents/index.ris.erb
<% for document in @documents
     next if !document.used_outside -%>
<%=  render(:partial => 'show.ris.erb', :locals => {:medium => document}) %>
<% end %>

app/views/documents/new.html.erb
<h1><%= ts('new.record', :what => 'Text-Website') %></h1>
<%= error_messages_for :medium %>
<%= error_messages_for :document %>
<%= form_for(:medium, :url => documents_path, :html => {:multipart => true}) do |f| %>
      <p><b><%= Typescript.human_attribute_name('uploaded_data').s %></b> (<%= ts 'document.description.typescript'.s %>)<br />
<%=   file_field :typescript, :uploaded_data %></p>
      <p><b><%= Typescript.human_attribute_name('thumbnail').s %></b> (<%= ts 'document.description.preview'.s %>)<br />
<%=   file_field :thumbnail, :uploaded_data %></p>
      <p><b><%= @medium.class.human_attribute_name(:photographer).s %></b><br />
<%=   f.collection_select(:photographer_id, @photographers, :id, :fullname, { :include_blank => true }, language_options) %> (<%= link_to ts('new.record', :what => AuthenticatedSystem::Person.model_name.human), new_authenticated_system_person_path, { :target => '_blank' } %>)</p>
      <p><b><%= @medium.class.human_attribute_name(:capture_device_model).s %></b><br />
<%=   f.select(:capture_device_model_id, @capture_device_models.collect {|m| [ "#{h(m.capture_device_maker.title)} - #{h(m.title)}", m.id ] }, { :include_blank => true }) %> (<%= link_to ts('manage.record', :what => CaptureDeviceMaker.model_name.human), capture_device_makers_path, { :target => '_blank' } %>)</p>
<%=   render :partial => 'media/form', :locals => {:f => f} %>
      <p><%= globalized_submit_tag 'creat.e.this' %></p>
<%  end %>
<p><%= link_to ts('back.to', :what => t('all.records', :what => Medium.model_name.human(:count => :many))), media_path %></p>

app/views/documents/paged_index.html.erb
<div id="primary">
<%= render :partial => 'media/main' %>
</div>
<div id="secondary">
<%= render :partial => 'documents/paged_index' %>
</div>
<div class="clear"></div>

app/views/documents/paged_index_full.html.erb
<div id="secondary">
<%= render :partial => 'documents/paged_index' %>
</div>
<div class="clear"></div>

app/views/documents/show.html.erb
<div id="secondary">
<%= render :partial => 'media/show' %>
</div>
<div class="clear"></div>

app/views/documents/show.ris.erb
TY - <%= @medium.resource_type.header %>
U5 - <%= @medium.id %>
<% titles = @medium.titles
   if !titles.first.nil? && !titles.first.title.blank? %>
TI - <%= titles.first.title %>
<% end
   if !titles.second.nil? && !titles.second.title.blank? %>
T1 - <%= titles.second.title %>
<% end 
   translated_titles = titles.collect{|t| t.translated_titles}.flatten
	 for title in translated_titles
		 if !title.title.blank? -%>
TT - <%= title.title %>
<%   end
   end
   if !@medium.photographer.nil? -%>
AU - <%= @medium.photographer.fullname %>
<% end 
   if !@medium.media_publisher.nil? && !@medium.media_publisher.publisher.nil? && !@medium.media_publisher.publisher.title.blank? -%>
PB - <%= @medium.media_publisher.publisher.title %>
<% end 
   caption = @medium.captions.first
	 if !caption.nil? && !caption.title.blank? -%>
CA - <%= caption.title %>
<% end 
   desc = @medium.descriptions.first
   if !desc.nil? && !desc.title.blank? -%>
N1 - <%= desc.title %>
<% end
   location = @medium.locations.first
   if !location.nil? && !location.feature.nil? & !location.feature.header.blank? -%>
CY - <%= location.feature.header %>
<% end
   @medium.media_category_associations.each do |mca|
     if !mca.category.nil? && !mca.category.header.blank? -%>
KW - <%= mca.category.header %>
<%   end
	 end -%>
ER -